# Site settings
title: Patrick Grady
author: Patrick Grady
email: patrick.a.grady@gmail.com
description: Design Portfolio of Patrick Grady
# baseurl: /pgrady-site # For gh-pages deploy
baseurl: "!BASE_URL!" # For local development


# Build settings
markdown: kramdown
exclude:
  - /node_modules
  - package.json
  - /assets/packages
  - bower.json
  - gulpfile.js
  - assets/sass/ #Compiling with Gulp
  - README.md
  - .gitignore
  - .bowerrc
