# Site settings
title: Patrick Grady
author: Patrick Grady
email: patrick.a.grady@gmail.com
description: Design Portfolio of Patrick Grady
permalink: none
# baseurl: /pgrady-site # For project gh-pages
baseurl: "" # For local dev and deployed site

# Build settings
markdown: kramdown
exclude:
  - /node_modules
  - package.json
  - /assets/packages
  - bower.json
  - gulpfile.js
  - assets/sass/ #Compiles with Gulp
  - README.md
  - .gitignore
  - .bowerrc
