# Site settings
title: Patrick Grady
author: Patrick Grady
email: mail@pgrady.com
description: Design Portfolio of Patrick Grady
url: "http://www.pgrady.com"

# Build settings
markdown: kramdown
exclude:
  - /node_modules
  - package.json
  - /assets/packages
  - bower.json
  - gulpfile.js
  - assets/sass/ #Compiling with Gulp
  - README.md
  - .gitignore
  - .bowerrc
